INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('iforster', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi', 'Ian', 'Forster');
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('jdoe', '$2a$11$3NO32OV1TGjap3xMpAEjmuiizitWuaSwUYz42aMtlxRliwJ8zm4Sm', 'John', 'Doe');
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('dforster', '$2a$11$pWo.t6dgYwyEu9xfzWo6wufApO/t3aJBD1TPgy49wt0VOEjt3fqvq', 'Dee', 'Forster');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('iforster', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('iforster', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('jdoe', 'USER');